### ISSUE TITLE
When a site uses a request context path, the redirect url after customer registration is incorrect

### ISSUE THREAD

**Issue by jefffischer** [BroadleafCommerce/LegacyDemoSite#104]
1. Launch site with a request context path (not ROOT.war)
2. Go to the site and register a new customer
3. Complete the customer registration form

You will be redirected to a url that does not have the request context path (incorrect)

**Comment by prabhatkataria** [comment]
I am also facing this problem. On my investigation I found that it happens when a controller returns string with view as "ajaxredirect", e.g. "ajaxredirect:/". In BroadleafThymeleafViewResolver class loadAjaxRedirectView method checks if the request is an ajax request. If the request is not an ajax request then a RedirectView object is returned with "contextRelative" field set to false.

Till this bug is resolved a work around can be done in RegisterController class by checking the returned string. If it contains "ajaxredirect" then change ajaxredirect to redirect.

**Comment by atamanroman** [comment]
I fixed this locally a few weeks ago. Somewhere in the code it's excplicitely stated that ajaxredirect does not consider the context. Just add it to the redirect url.
