### ISSUE TITLE
Add to cart fails when product is featured twice on same page

### ISSUE THREAD

**Issue by watermelonjuice** [BroadleafCommerce/LegacyDemoSite#128]
1) Add product 'xyz' to category 1.
2) Make product 'xyz' a featured product that appears in the right sidebar when viewing category 1.
3) Attempt to add the product to the cart.
4) Silent user side error is given with no error in server logs.

**Comment by brundonsmith** [comment]
If the error you're talking about it "dotdotdot: No element found for "ul#products li .content".", then I think it's an appropriate one that doesn't need to be gotten rid of. What it's saying is that it can't find any products in the normal products section (non-featured), because the only product in the category is featured. It's valid that it can't find any, and it's also not a big enough deal to be logged, so I would say that the error is what it should be.
