### ISSUE TITLE
Javascript error on login page

### ISSUE THREAD

**Issue by brundonsmith** [BroadleafCommerce/LegacyDemoSite#143]
The login page works, but as soon as it loads I'm getting errors in the console, starting with "unexpected token '{'", followed by over a dozen "cannot read property '_____' of undefined" errors. This is on 3.1.x and I didn't ever notice it on 3.0.x, though I haven't yet looked for it on 3.0.x.

**Comment by phillipuniverse** [comment]
@brundonsmith for future reference, open any admin-related bugs on the framework since all of those are managed there. DemoSite is more for issues relating to site-level problems in DemoSite (add to cart, checkout, etc). Those in turn might actually be framework issues and so sometimes those end up being opened in the framework as well.

Open a new ticket in the framework and I'll add some comments around it.
