### ISSUE TITLE
Multiple Bugs

### ISSUE THREAD

**Issue by c0nscience** [BroadleafCommerce/LegacyDemoSite#4]
Hi,

I have tested the demoSite develop branche the whole night and try to get it correctly to work, but I don't get it.

It's just a guess, but I think that the ant task for renaming didn't work flawless and the combined module seems not to work as well.

I got multiple errors, after runing the ant task on the master or the develop branch for example on the master branch I get a startup error, that the loginController bean could not initialized, because the loginService bean could not found. But I changed nothing else on the code base, so the bug seams to lie a bit deeper.

And for example on the develop branch the solr server produced some errors and some more issues.

Have you tested the ant task ? If I did not run it the master branch work flawless with 'ant jetty-demo', but not on the combined module. And on the develop branch it seems, that without renaming the project and module there are a bit less errors.

**Comment by jefffischer** [comment]
I haven't tested the rename ant task stuff lately, so there could definitely be an issue there. However, we use the develop demosite daily without the package renaming and don't run into any problems. More information would be required on your errors to give you any real guidance. Please post any issues you run into on our public forums and the community or a broadleaf staffer can assist you.

Thx.

Jeff Fischer
Broadleaf Commerce
www.broadleafcommerce.orghttp://www.broadleafcommerce.org/
jfischer@broadleafcommerce.orgmailto:marketing@broadleafcommerce.org

On Jan 31, 2013, at 9:39 AM, c0nscience <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

I have tested the demoSite develop branche the whole night and try to get it correctly to work, but I don't get it.

It's just a guess, but I think that the ant task for renaming didn't work flawless and the combined module seems not to work as well.

I got multiple errors, after runing the ant task on the master or the develop branch for example on the master branch I get a startup error, that the loginController bean could not initialized, because the loginService bean could not found. But I changed nothing else on the code base, so the bug seams to lie a bit deeper.

And for example on the develop branch the solr server produced some errors and some more issues.

Have you tested the ant task ? If I did not run it the master branch work flawless with 'ant jetty-demo', but not on the combined module. And on the develop branch it seems, that without renaming the project and module there are a bit less errors.

**Comment by c0nscience** [comment]
Ok, then I did not use the renaming task until you have reviewed it :)
