### ISSUE TITLE
Improve and Update DemoSite Getting Started Documentation

### ISSUE THREAD

**Issue by yoeluk** [BroadleafCommerce/LegacyDemoSite#74]
I have lost 4 solid hours with this starter project. It does not run as the guide says! Although it will run the demo in Eclipse it will also produce an abundant of errors and in IntelliJ which was my aim it will not run at all. Although one could run the jetty-demo as described without problems. Certainly not a solid start if the rest doesn't work! Also the guide is out-of-date since there are no artifact called combined.

**Comment by bpolster** [comment]
@yoeluk Thank you for your feedback.   It is a high priority issue for us to review and update the DemoSite Getting Started documentation.   

Also, edited the title of this ticket to reflect the work involved.

**Comment by bpolster** [comment]
Comment received at Broadleaf Info ... 

"...  there seems to an issue. Specifically, with a fresh install of the BroadleafCommerce-3.0.x demo, on current versions of mysql and tomcat7, if you flip the hbm2ddl.auto to create, start and then stop tomcat, then flip the hbm2ddl.auto to validate and try to start again, it wont start due to boolean tinyint issues."

This is because of https://github.com/BroadleafCommerce/BroadleafCommerce/issues/189 (for tracking purposes)
